<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0">
  <channel>
    <title>$title$</title>
    <description>
      This feed was constructed by automated analysis of $articleCount$ articles from $feedCount$
      news sources. No humans were involved in the selection and classification of these headlines.
    </description>
    <language>en-gb</language>
    $topics:item()$
  </channel>
</rss>